version: "3.7"

services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=role_controller
    volumes: 
      - pgdata:/data/postgres    
  app:
   build: .
   container_name: role_controller
   ports:
     - 3333:3333
   volumes: 
     - .:/usr/app
   links:
       - db_postgres
   depends_on:
       - db_postgres      
volumes: 
  pgdata:
    driver: local 